# Generated by Django 3.0.4 on 2020-03-27 15:11

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200327_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateTimeField(),
        ),
    ]
