# Generated by Django 3.0.4 on 2020-04-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20200403_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug_hash',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=15),
        ),
    ]
