# Generated by Django 3.0.4 on 2020-04-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_auto_20200403_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
