# Generated by Django 3.0.4 on 2020-04-03 10:38

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_postcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.get_image_filename, verbose_name='Image'),
        ),
    ]
